// Code generated by "stringer -type=SegmentedType"; DO NOT EDIT.

package segmentation

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SegmentedBoth-0]
	_ = x[SegmentedTransmit-1]
	_ = x[SegmentedReceive-2]
	_ = x[NoSegmentation-3]
}

const _SegmentedType_name = "SegmentedBothSegmentedTransmitSegmentedReceiveNoSegmentation"

var _SegmentedType_index = [...]uint8{0, 13, 30, 46, 60}

func (i SegmentedType) String() string {
	if i >= SegmentedType(len(_SegmentedType_index)-1) {
		return "SegmentedType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SegmentedType_name[_SegmentedType_index[i]:_SegmentedType_index[i+1]]
}
